# Generated by Django 2.2.5 on 2021-04-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='doDone',
            field=models.BooleanField(default=False),
        ),
    ]
